# Specify project environments
env:
  es6: true
  browser: true

# Specify rule extensions
extends:
  - 'plugin:@wordpress/eslint-plugin/recommended-with-formatting'

# Configure rules
rules:
    no-undef: warn
    no-unused-vars: warn
    no-bitwise: warn
    no-alert: warn
    no-console:
      - error
      - allow:
        - warn
        - error
    jsx-a11y/label-has-associated-control: warn
    jsx-a11y/label-has-for: off

# Specify global variables to ignore
# Some of these aren't really globals, but this is useful for ignoring no-undef for class vars etc.
globals:
  CLCardVimeo: readonly
  CLCreateVimeoPlayers: readonly
  CLHeroVimeo: readonly
  CLVideoVimeo: readonly
  CLVimeo: readonly
  CLYT: readonly
  jQuery: readonly
  onYouTubePlayerAPIReady: readonly
  tinymce: readonly
  URICL: readonly
  URIComponentLibrary: readonly
  URIWYSIWYG: readonly
  Vimeo: readonly
  YT: readonly

# Specify files and directories to ignore
ignorePatterns:
    - 'gulpfile.js'
    - 'js/cl.built.js'
    - 'js/blocks.built.js'
    - 'js/wysiwyg/noneditable/**'
    - 'node_modules/'
    - 'webpack.config.js'
